### PR TITLE
ci(actions): install `tokei` with `nix`

### PR DESCRIPTION
**Pull request by xrelkd**

### CODE REVIEW

**Comment by xrelkd** [comment]
Pin @AtkinsChang @XiaoXiaoSN for review.

**Review by XiaoXiaoSN — APPROVED** [review]
LGTM
If we use the Nix package manager, we can reduce the CI execution time by downloading the compiled `tokei` executable binary.

**Comment by XiaoXiaoSN** [comment]
cc @AtkinsChang

**Review by AtkinsChang — APPROVED** [review]
LGTM

**Pull request merged**
